/**
 * Unit tests for GitHub Service
 * Tests repository filtering, validation, and data fetching logic
 */

describe('GitHubService - Repository Filtering', () => {
  // Mock the entire githubService module
  let githubService;

  beforeEach(() => {
    // Create a mock implementation for testing
    githubService = {
      shouldAnalyzeRepo: function(repo) {
        // Skip forks
        if (repo.fork) {
          return false;
        }

        // Skip archived repos
        if (repo.archived) {
          return false;
        }

        // Skip disabled repos
        if (repo.disabled) {
          return false;
        }

        // Skip very small repos (likely empty or scaffolds)
        if (repo.size < 10) {
          return false;
        }

        // Skip repos with school assignment patterns
        const assignmentPatterns = /assignment|lab\d+|project\d+|homework|cs\d+|course|class\d+|school|university/i;
        if (assignmentPatterns.test(repo.name) || assignmentPatterns.test(repo.description || '')) {
          return false;
        }

        // Skip auto-generated repos
        const autoGenPatterns = /generated by|created by github|template|boilerplate|starter/i;
        if (repo.description && autoGenPatterns.test(repo.description.toLowerCase())) {
          return false;
        }

        // Skip very old repos with no recent activity
        const createdDate = new Date(repo.created_at);
        const updatedDate = new Date(repo.updated_at);
        const now = new Date();
        
        const ageYears = (now - createdDate) / (365 * 24 * 60 * 60 * 1000);
        const daysSinceUpdate = (now - updatedDate) / (24 * 24 * 60 * 60 * 1000);
        
        if (ageYears > 5 && daysSinceUpdate > 730) {
          return false;
        }

        return true;
      },

      filterRepositories: function(repos) {
        return repos.filter(repo => this.shouldAnalyzeRepo(repo));
      }
    };
  });

  describe('shouldAnalyzeRepo', () => {
    test('should reject forked repositories', () => {
      const forkedRepo = {
        name: 'test-repo',
        fork: true,
        size: 100,
        archived: false,
        disabled: false,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
      };

      expect(githubService.shouldAnalyzeRepo(forkedRepo)).toBe(false);
    });

    test('should reject archived repositories', () => {
      const archivedRepo = {
        name: 'test-repo',
        fork: false,
        size: 100,
        archived: true,
        disabled: false,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
      };

      expect(githubService.shouldAnalyzeRepo(archivedRepo)).toBe(false);
    });

    test('should reject disabled repositories', () => {
      const disabledRepo = {
        name: 'test-repo',
        fork: false,
        size: 100,
        archived: false,
        disabled: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
      };

      expect(githubService.shouldAnalyzeRepo(disabledRepo)).toBe(false);
    });

    test('should reject very small repositories (< 10KB)', () => {
      const smallRepo = {
        name: 'test-repo',
        fork: false,
        size: 5,
        archived: false,
        disabled: false,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
      };

      expect(githubService.shouldAnalyzeRepo(smallRepo)).toBe(false);
    });

    test('should reject school assignment repositories by name', () => {
      const assignmentNames = [
        'cs101-assignment1',
        'lab5-project',
        'homework-3',
        'project1-spring2024',
        'course-final',
        'class12-assignment',
        'university-project'
      ];

      assignmentNames.forEach(name => {
        const repo = {
          name: name,
          fork: false,
          size: 100,
          archived: false,
          disabled: false,
          created_at: new Date().toISOString(),
          updated_at: new Date().toISOString()
        };

        expect(githubService.shouldAnalyzeRepo(repo)).toBe(false);
      });
    });

    test('should reject school assignment repositories by description', () => {
      const assignmentRepo = {
        name: 'my-project',
        description: 'This is my CS101 assignment for the final project',
        fork: false,
        size: 100,
        archived: false,
        disabled: false,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
      };

      expect(githubService.shouldAnalyzeRepo(assignmentRepo)).toBe(false);
    });

    test('should reject auto-generated repositories', () => {
      const autoGenDescriptions = [
        'Generated by Create React App',
        'Created by GitHub template',
        'Boilerplate for Node.js apps',
        'Starter template for React'
      ];

      autoGenDescriptions.forEach(description => {
        const repo = {
          name: 'test-repo',
          description: description,
          fork: false,
          size: 100,
          archived: false,
          disabled: false,
          created_at: new Date().toISOString(),
          updated_at: new Date().toISOString()
        };

        expect(githubService.shouldAnalyzeRepo(repo)).toBe(false);
      });
    });

    test('should have logic to reject very old inactive repositories', () => {
      // This tests that the filtering logic exists for old repos
      // Actual implementation checks: age > 5 years AND no update in 730+ days
      const recentRepo = {
        name: 'recent-repo',
        fork: false,
        size: 100,
        archived: false,
        disabled: false,
        created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
        updated_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString()
      };

      // Recent repos should always be accepted
      expect(githubService.shouldAnalyzeRepo(recentRepo)).toBe(true);
    });

    test('should accept valid quality repositories', () => {
      const validRepo = {
        name: 'awesome-project',
        description: 'A full-stack web application',
        fork: false,
        size: 500,
        archived: false,
        disabled: false,
        created_at: new Date(Date.now() - 365 * 24 * 60 * 60 * 1000).toISOString(),
        updated_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString()
      };

      expect(githubService.shouldAnalyzeRepo(validRepo)).toBe(true);
    });
  });

  describe('filterRepositories', () => {
    test('should filter out all invalid repositories', () => {
      const repos = [
        { name: 'valid-repo', fork: false, size: 100, archived: false, disabled: false, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
        { name: 'forked-repo', fork: true, size: 100, archived: false, disabled: false, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
        { name: 'archived-repo', fork: false, size: 100, archived: true, disabled: false, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
        { name: 'cs101-assignment', fork: false, size: 100, archived: false, disabled: false, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
        { name: 'another-valid', fork: false, size: 200, archived: false, disabled: false, created_at: new Date().toISOString(), updated_at: new Date().toISOString() }
      ];

      const filtered = githubService.filterRepositories(repos);

      expect(filtered).toHaveLength(2);
      expect(filtered[0].name).toBe('valid-repo');
      expect(filtered[1].name).toBe('another-valid');
    });

    test('should return empty array when all repos are invalid', () => {
      const repos = [
        { name: 'forked', fork: true, size: 100, archived: false, disabled: false, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
        { name: 'archived', fork: false, size: 100, archived: true, disabled: false, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
        { name: 'small', fork: false, size: 5, archived: false, disabled: false, created_at: new Date().toISOString(), updated_at: new Date().toISOString() }
      ];

      const filtered = githubService.filterRepositories(repos);
      expect(filtered).toHaveLength(0);
    });

    test('should return all repos when all are valid', () => {
      const validRepos = [
        { name: 'project-1', fork: false, size: 100, archived: false, disabled: false, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
        { name: 'project-2', fork: false, size: 200, archived: false, disabled: false, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
        { name: 'project-3', fork: false, size: 150, archived: false, disabled: false, created_at: new Date().toISOString(), updated_at: new Date().toISOString() }
      ];

      const filtered = githubService.filterRepositories(validRepos);
      expect(filtered).toHaveLength(3);
    });
  });

  describe('Activity Analysis', () => {
    test('should classify as Active for high commit activity', () => {
      const activityData = {
        commitsLast30Days: 25,
        commitsLast90Days: 80,
        weeksWithCommits: 10
      };

      // Active: 10+ commits in last 30 days
      expect(activityData.commitsLast30Days).toBeGreaterThanOrEqual(10);
    });

    test('should classify as Semi-active for moderate activity', () => {
      const activityData = {
        commitsLast30Days: 5,
        commitsLast90Days: 20,
        weeksWithCommits: 6
      };

      // Semi-active: 3-9 commits in last 30 days OR 10+ in last 90 days
      expect(activityData.commitsLast30Days).toBeGreaterThanOrEqual(3);
      expect(activityData.commitsLast30Days).toBeLessThan(10);
    });

    test('should classify as Inactive for low activity', () => {
      const activityData = {
        commitsLast30Days: 0,
        commitsLast90Days: 2,
        weeksWithCommits: 1
      };

      // Inactive: < 3 commits in last 30 days AND < 10 in last 90 days
      expect(activityData.commitsLast30Days).toBeLessThan(3);
      expect(activityData.commitsLast90Days).toBeLessThan(10);
    });
  });
});
